# Generated by Django 5.2.8 on 2025-11-10 00:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(choices=[('AI', 'Ai'), ('REAL', 'Real')], max_length=8)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('model_version', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-processed_at',),
            },
        ),
    ]
